
<?php
$id = $_GET['id'] ?? null;

$hardcoded_venues = [
  [
    'id'       => 1,
    'name'     => 'Paradiso Terrestre',
    'location' => 'Molino, Cavite City',
    'price'    => 35000,
    'cap'      => 500,
    'standing' => 500,
    'catering' => false,
    'rating'   => 4.8,
    'reviews'  => 36,
    'response' => '2 hrs',
    'image'    => 'assets/images/paradiso1.jpg',
    'gallery'  => [
      ['label' => 'Garden Terrace', 'src' => 'assets/images/paradiso1.jpg'],
      ['label' => 'Main Hall',    'src' => 'assets/images/paradiso2.jpg'],
      ['label' => 'Al Fresco',    'src' => 'assets/images/paradiso3.jpg'],
      ['label' => 'Bridal Suite', 'src' => 'assets/images/paradiso4.jpg'],
      ['label' => 'Ballroom',     'src' => 'assets/images/paradiso5.jpg'],
    ],
    'desc'     => 'Paradiso Terrestre is the perfect venue for every occasion — whether you\'re planning a corporate event, celebrating a wedding, or hosting a debut. With its breathtaking ambiance and character-filled spaces, it consistently attracts elegant events of all kinds. Located along the National Highway of Molino, Cavite City, just 10 minutes away from Alabang via the newly constructed Daang Hari & MCX.',
    'why'      => [
      'Multi-functional event space for any occasion',
      'Easy access to public transportation & major highways',
      'Large outdoor and indoor venues available',
      'Just 10 minutes from Alabang via Daang Hari & MCX',
    ],
    'amenities' => [
      ['icon' => '🅿️', 'label' => 'Free Parking'],
      ['icon' => '❄️', 'label' => 'Air Conditioning'],
      ['icon' => '🎤', 'label' => 'Sound System'],
      ['icon' => '💡', 'label' => 'Stage Lighting'],
      ['icon' => '📽️', 'label' => 'Projector & Screen'],
      ['icon' => '♿', 'label' => 'Wheelchair Access'],
      ['icon' => '🛡️', 'label' => '24/7 Security'],
      ['icon' => '📶', 'label' => 'Free Wi-Fi'],
    ],
    'reviews_list' => [
      ['name' => 'Maria Reyes',    'initials' => 'MR', 'color' => '#6366f1', 'date' => 'March 2026 · Wedding', 'rating' => 5, 'text' => 'Absolutely beautiful venue! The outdoor garden was perfect for our wedding ceremony. The staff were attentive and the whole place was immaculate. Highly recommend!'],
      ['name' => 'Juan dela Cruz', 'initials' => 'JD', 'color' => '#10b981', 'date' => 'January 2026 · Corporate Event', 'rating' => 4, 'text' => 'Great venue for our annual company event. Accessible from Metro Manila and the halls are very spacious. The sound system and lighting setup were impressive.'],
    ],
  ],
  [
    'id'       => 2,
    'name'     => 'Blue Gardens',
    'location' => 'Makati City, Metro Manila',
    'price'    => 60000,
    'cap'      => 250,
    'standing' => 300,
    'catering' => true,
    'rating'   => 4.9,
    'reviews'  => 52,
    'response' => '1 hr',
    'image'    => 'assets/images/gardens1.jpg',
    'gallery'  => [
      ['label' => 'Garden Terrace', 'src' => 'assets/images/gardens1.jpg'],
      ['label' => 'Main Hall',    'src' => 'assets/images/gardens2.jpg'],
      ['label' => 'Al Fresco',    'src' => 'assets/images/gardens3.jpg'],
      ['label' => 'Bridal Suite', 'src' => 'assets/images/gardens4.jpg'],
      ['label' => 'Ballroom',     'src' => 'assets/images/gardens5.jpg'],
    ],
    'desc'     => 'Blue Gardens is a luxury indoor ballroom ideal for proms, galas, and formal events. Situated in the heart of Makati, it offers world-class service and an elegant atmosphere that transforms any gathering into an unforgettable experience.',
    'why'      => [
      'Luxury ballroom with premium interior design',
      'In-house catering with curated menus available',
      'Prime Makati location — walking distance from hotels',
      'Dedicated event coordinator for every booking',
    ],
    'amenities' => [
      ['icon' => '🅿️', 'label' => 'Valet Parking'],
      ['icon' => '❄️', 'label' => 'Central Air Conditioning'],
      ['icon' => '🎤', 'label' => 'Professional Sound System'],
      ['icon' => '🍽️', 'label' => 'In-House Catering'],
      ['icon' => '📽️', 'label' => 'LED Wall Display'],
      ['icon' => '♿', 'label' => 'Wheelchair Access'],
      ['icon' => '💐', 'label' => 'Floral Arrangements'],
      ['icon' => '📶', 'label' => 'High-Speed Wi-Fi'],
    ],
    'reviews_list' => [
      ['name' => 'Angela Santos', 'initials' => 'AS', 'color' => '#f59e0b', 'date' => 'February 2026 · Prom Night',  'rating' => 5, 'text' => 'Our prom was absolutely magical here! The ballroom looked stunning and the staff were so accommodating. Everyone had an amazing night!'],
      ['name' => 'Carlo Mendoza', 'initials' => 'CM', 'color' => '#3b82f6', 'date' => 'December 2025 · Gala Dinner', 'rating' => 5, 'text' => 'Top-notch venue for formal events. The food was excellent and the ambiance was perfect. Worth every peso!'],
    ],
  ],
  [
    'id'       => 3,
    'name'     => 'The Green Lounge Events Place',
    'location' => 'Quezon City, Metro Manila',
    'price'    => 45000,
    'cap'      => 300,
    'standing' => 400,
    'catering' => false,
    'rating'   => 4.7,
    'reviews'  => 28,
    'response' => '3 hrs',
    'image'    => 'assets/images/lounge1.jpg',
    'gallery'  => [
      ['label' => 'Garden Terrace', 'src' => 'assets/images/lounge1.jpg'],
      ['label' => 'Main Hall',    'src' => 'assets/images/lounge2.jpg'],
      ['label' => 'Al Fresco',    'src' => 'assets/images/lounge3.jpg'],
      ['label' => 'Bridal Suite', 'src' => 'assets/images/lounge4.jpg'],
      ['label' => 'Ballroom',     'src' => 'assets/images/lounge5.png'],
    ],
    'desc'     => 'The Green Lounge is a modern event space with a minimalist aesthetic and striking architectural lighting. Located in Quezon City, it is perfect for contemporary celebrations, product launches, and intimate gatherings that demand a stylish and versatile backdrop.',
    'why'      => [
      'Modern minimalist design with architectural lighting',
      'Flexible layout — ideal for any event type',
      'Located along a major QC thoroughfare',
      'Ample free parking for up to 100 vehicles',
    ],
    'amenities' => [
      ['icon' => '🅿️', 'label' => 'Free Parking (100 slots)'],
      ['icon' => '❄️', 'label' => 'Industrial AC System'],
      ['icon' => '🎤', 'label' => 'Premium Sound System'],
      ['icon' => '💡', 'label' => 'Architectural Lighting'],
      ['icon' => '📽️', 'label' => 'Twin Projectors'],
      ['icon' => '♿', 'label' => 'Wheelchair Access'],
      ['icon' => '🛡️', 'label' => '24/7 Security'],
      ['icon' => '📶', 'label' => 'Free Wi-Fi'],
    ],
    'reviews_list' => [
      ['name' => 'Bea Villanueva', 'initials' => 'BV', 'color' => '#ec4899', 'date' => 'March 2026 · Birthday Party',   'rating' => 5, 'text' => 'Such a stunning venue! The lighting alone makes it worth it. Everyone kept asking where we had the party. Will definitely book again!'],
      ['name' => 'Paolo Cruz',     'initials' => 'PC', 'color' => '#14b8a6', 'date' => 'November 2025 · Product Launch', 'rating' => 4, 'text' => 'Very professional setup. The space is flexible and the staff helped us configure the layout perfectly for our launch event.'],
    ],
  ],
];